export  enum AuthActions {
  LOGIN_REQUEST_LOADING = 'LOGIN REQUEST LOADING',
  LOGIN_REQUEST_ERROR = 'LOGIN REQUEST ERROR',
  LOGIN_REQUEST_SUCCESS = 'LOGIN REQUEST SUCCESS',

  LOGOUT_REQUEST_LOADING = 'LOGOUT REQUEST LOADING',
  LOGOUT_REQUEST_ERROR = 'LOGOUT REQUEST ERROR',
  LOGOUT_REQUEST_SUCCESS = 'LOGOUT REQUEST SUCCESS'
}
export  enum LoadingModalActions{
  LOADING ='LOADING',
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
  CLOSE = 'CLOSE'
}
export  enum FilterActions{
  FILTER_TEAM='FILTER TEAM',
  FILTER_ASSET = 'FILTER ASSET',
  FILTER_TASK = 'FILTER TASK',
  FILTER_EMPLOYEE = 'FILTER EMPLOYEE',
  FILTER_TASK_BY_STATE = 'FILTER TASK BY STATE'
}


export enum TalentActions {
  TALENT_LIST_LOADING = 'TALENT LIST LOADING',
  TALENT_LIST_ERROR = 'TALENT LIST ERROR',
  TALENT_LIST_SUCCESS = 'TALENT LIST SUCCESS'
}

export enum ProfileActions {
  PROFILE_LIST_LOADING = 'PROFILE LIST LOADING',
  PROFILE_LIST_ERROR = 'PROFILE LIST ERROR',
  PROFILE_LIST_SUCCESS = 'PROFILE LIST SUCCESS'
}