export  enum AuthActions {
  AUTH_REQUEST_LOADING = 'AUTH REQUEST LOADING',
  AUTH_REQUEST_ERROR = 'AUTH REQUEST ERROR',
  AUTH_REQUEST_SUCCESS = 'AUTH REQUEST SUCCESS',
}
export  enum LoadingModalActions{
  LOADING ='LOADING',
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
  CLOSE = 'CLOSE'
}
export  enum FilterActions{
  FILTER_TEAM='FILTER TEAM',
  FILTER_ASSET = 'FILTER ASSET',
  FILTER_TASK = 'FILTER TASK',
  FILTER_EMPLOYEE = 'FILTER EMPLOYEE',
  FILTER_TASK_BY_STATE = 'FILTER TASK BY STATE'
}
